# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23.4.0'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
      
    - name: Test
      run: dotnet test --no-build -c Release --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

    - name: ReportGenerator
      uses: im-open/code-coverage-report-generator@4
      with:
        reports: '*/**/coverage.cobertura.xml'
        targetdir: './coverage-results'
        title: dotnet code coverage
        reporttypes: 'MarkdownSummary;'

    - name: Upload coverage summary artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-results
        path: ./coverage-results/Summary.md
