# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23.4.0'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
      
    - name: Test
      run: dotnet test --no-build -c Release --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

    - name: ReportGenerator
      uses: im-open/code-coverage-report-generator@4
      with:
        reports: '*/**/coverage.cobertura.xml'
        targetdir: './coverage-results'
        title: dotnet code coverage
        reporttypes: 'MarkdownSummary;'

    - name: Create a status check for the code coverage results
      id: dotnet-coverage-check
      uses: im-open/process-code-coverage-summary@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        summary-file: './coverage-results/Summary.md'
        #create-status-check: true
        create-pr-comment: true
        update-comment-if-one-exists: true
        update-comment-key: 'dotnet'
        ignore-threshold-failures: false 
        line-threshold: 80
        branch-threshold: 80
